rabbitmq:
  host: ${RABBITMQ_HOST:172.17.0.2}
  queueName: ${RABBITMQ_QUEUE_NAME:apix-notification-queue}

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID:your_account_sid}
  authToken: ${TWILIO_AUTH_TOKEN:your_auth_token}
  from: ${TWILIO_FROM_AUTH_TOKEN:your_twilio_phone}
