rabbitmq:
  host: ${RABBITMQ_HOST}
  queueName: ${RABBITMQ_QUEUE_NAME:apix-notification-queue}

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  from: ${TWILIO_FROM_PHONE}
